name: C++ Build and Test with YARA-X Dependency

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install additional dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake pkg-config

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-c
        run: cargo install cargo-c

      - name: Clone YARA-X
        run: |
          git clone https://github.com/VirusTotal/yara-x.git
          cd yara-x
          cargo cinstall -p yara-x-capi --release

      - name: Verify YARA-X installation
        run: |
          echo '#include <yara_x.h>' > test.c
          echo 'int main() { YRX_RULES* rules; yrx_compile("rule dummy { condition: true }", &rules); yrx_rules_destroy(rules); }' >> test.c
          gcc `pkg-config --cflags yara_x_capi` `pkg-config --libs yara_x_capi` test.c

      - name: Set up C++ compiler
        uses: actions/setup-cpp@v2
        with:
          compiler: clang++ 


      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make

      - name: Run tests with CTest
        run: |
          cd build
          ctest --output-on-failure
